Inject constructor counter
HTTPArchive/custom-metrics pull request #35
Opened 2022-05-27 18:55 UTC by kevinfarrugia

Required for [JavaScript 2022](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2880)

Added support to count the number of times the Worker constructor is called. Code is set up to support additional constructors if needed.

Test: https://webpagetest.httparchive.org/result/220527_JN_G/1/details/#waterfall_view_step1

Uses custom metric:
```
[workers]
return JSON.stringify({
    workers: (() => {
        return httparchive_observers.constructor_stacks["Worker"];
    })()
});
```

Results include:

workers | 1
-- | --

2022-05-28 03:28 UTC, rviscomi commented
I think all that's needed is a minimal change to add `Worker` to the `OBSERVERS` list. There was a bug in the implementation that I recently fixed in #32 where top-level properties under `window` weren't being observed properly. That might by why you thought you needed a separate implementation for constructors.

Here's a [test](https://webpagetest.httparchive.org/result/220528_MP_4/1/details/#waterfall_view_step1) where I just added the constructor name to the const, and it worked.

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/1120896/170808118-f210547b-c3f5-4320-9cbb-831a46c34bf2.png">

2022-05-28 22:46 UTC, kevinfarrugia commented
Thank you @rviscomi . I have updated the PR and it seems to work correctly.

2022-05-29 02:56 UTC, rviscomi commented
Did you push your changes? I'm still seeing the separate `CONSTRUCTORS` array.

2022-05-29 12:48 UTC, kevinfarrugia commented
😴. Updated.

2022-05-29 13:19 UTC, rviscomi requested changes

2022-05-29 13:19 UTC, rviscomi commented on dist/javascript.js
> +    workers: (() => {
Similarly I think we can rely on the `observers.js` custom metric to extract this value. Otherwise LGTM.

2022-05-29 14:49 UTC, kevinfarrugia commented
Updated test using `observers.js`.

https://webpagetest.httparchive.org/result/220529_6B_M/1/details/#waterfall_view_step1

2022-05-29 21:26 UTC, rviscomi approved these changes

2022-05-29 21:26 UTC, merged